spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nhatnam_finefoods
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Hai14031993@@@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

server:
  port: 9261

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000
      refresh-token:
        expiration: 604800000

app:
  attendance:
    upload-dir: ~/Desktop/nhatnam-finefoods-storage/attendance

misa:
  enabled: false
  app-id: ""
  org-company-code: ""
  base-url: "https://openapi.misa.com.vn"
  # access-token-url: "https://..."   # sẽ thêm sau
  # client-id: ""
  # client-secret: ""
  default-branch-id: ""               # ID chi nhánh trên MISA
  default-stock-code: "KPQ"           # Mã kho mặc định
  default-stock-name: "Kho Phổ Quang" # Tên kho mặc định

